# compilers and constant flags
CC = cc
CFLAGS = -Wall -Werror -Wextra -Wpedantic -Wextra-semi -Wnull-dereference -Wsuggest-override -Wconversion -Wshadow -O2

webget: webget.c
	$(CC) -o webget webget.c $(CFLAGS)