# compilers and constant flags
CC = cc
CFLAGS = -Wall -Werror -Wextra -Wpedantic -Wextra-semi -Wnull-dereference -Wsuggest-override -Wconversion -Wshadow -O2

http: http.c
	$(CC) -o http http.c $(CFLAGS)